---
engines:
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.rb"
exclude_paths:
- spec/
prepare:
  fetch:
  - url: https://raw.githubusercontent.com/codeclimate/styleguide/master/ruby/rubocop.yml
    path: .cc_rubocop.yml
