FROM codeclimate/codeclimate-grep

WORKDIR /usr/src/app

RUN  bundle install --quiet --no-cache --with=test --system && \
  chown -R app:app /usr/local/bundle && \
  rm -fr ~/.gem ~/.bundle ~/.wh..gem && \
  gem cleanup
